// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'longTransitionDuration': string;
  'shortTransitionDuration': string;
}
export const cssExports: CssExports;
export default cssExports;
